name: py-bio
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=1.4.0
  - aiohttp=3.8.5
  - aiosignal=1.3.1
  - anndata=0.9.1
  - anyio=3.7.1
  - aom=3.5.0
  - arpack=3.7.0
  - arrow=1.2.3
  - asciitree=0.3.3
  - asttokens=2.2.1
  - async-timeout=4.0.3
  - attrs=23.1.0
  - aws-c-auth=0.7.0
  - aws-c-cal=0.6.0
  - aws-c-common=0.8.23
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.1
  - aws-c-http=0.7.11
  - aws-c-io=0.13.28
  - aws-c-mqtt=0.8.14
  - aws-c-s3=0.3.13
  - aws-c-sdkutils=0.1.11
  - aws-checksums=0.1.16
  - aws-crt-cpp=0.20.3
  - aws-sdk-cpp=1.10.57
  - backcall=0.2.0
  - backoff=2.2.1
  - backports=1.0
  - backports.cached-property=1.0.2
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - blessed=1.19.1
  - blosc=1.21.4
  - bokeh=3.2.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.10.2
  - ca-certificates=2023.7.22
  - cachecontrol=0.12.11
  - cachecontrol-with-filecache=0.12.11
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfitsio=4.2.0
  - charls=2.4.2
  - charset-normalizer=3.1.0
  - cleo=2.0.1
  - click=8.1.6=unix_pyh707e725_0
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.3
  - contextlib2=21.6.0
  - contourpy=1.1.0
  - crashtest=0.4.1
  - croniter=1.4.1
  - cryptography=41.0.2
  - cycler=0.11.0
  - cytoolz=0.12.2
  - dask=2023.9.0
  - dask-core=2023.9.0
  - dask-image=2023.8.1
  - dateutils=0.6.12
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.6.7
  - decorator=5.1.1
  - deepdiff=6.3.1
  - distlib=0.3.7
  - distributed=2023.9.0
  - dm-tree=0.1.8
  - docrep=0.3.2
  - dulwich=0.21.5
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - exceptiongroup=1.1.2
  - executing=1.2.0
  - expat=2.5.0
  - fastapi=0.100.1
  - fasteners=0.17.3
  - filelock=3.12.2
  - fonttools=4.40.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2023.6.0
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.6.0
  - glpk=5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - h11=0.14.0
  - h5py=3.9.0=nompi_py310hcca72df_101
  - hdf5=1.14.1=nompi_h4f84152_100
  - html5lib=1.1
  - icu=72.1
  - idna=3.4
  - imageio=2.31.1
  - importlib-metadata=6.7.0
  - importlib_metadata=6.7.0
  - importlib_resources=6.0.0
  - inflect=7.0.0
  - inquirer=3.1.3
  - ipykernel=6.23.3
  - ipython=8.14.0
  - itsdangerous=2.1.2
  - jaraco.classes=3.3.0
  - jax=0.4.13
  - jaxlib=0.4.12=cpu_py310hc0ddb09_1
  - jedi=0.18.2
  - jeepney=0.8.0
  - jinja2=3.1.2
  - joblib=1.3.0
  - jsonschema=4.18.6
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.3.0
  - jupyter_core=5.3.1
  - jxrlib=1.1
  - keyring=23.13.1
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy_loader=0.3
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - leidenalg=0.9.1
  - lerc=4.0.0
  - libabseil=20230125.3=cxx17_h59595ed_0
  - libaec=1.0.6
  - libarrow=12.0.1
  - libavif=0.11.1
  - libblas=3.9.0=17_linux64_openblas
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0=17_linux64_openblas
  - libcrc32c=1.1.2
  - libcurl=8.1.2
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.4
  - libgomp=13.1.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.54.3
  - libhwloc=2.9.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0=17_linux64_openblas
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libnuma=2.0.16
  - libopenblas=0.3.23=pthreads_h80387f5_0
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libstdcxx-ng=13.1.0
  - libthrift=0.18.1
  - libtiff=4.5.1
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.44.2
  - libwebp-base=1.3.0
  - libxcb=1.15
  - libxml2=2.10.4
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - lightning=2.0.6
  - lightning-cloud=0.5.37
  - lightning-utilities=0.9.0
  - locket=1.0.0
  - lockfile=0.12.2
  - loompy=3.0.6
  - lz4=4.3.2
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - matplotlib-scalebar=0.8.1
  - mdurl=0.1.0
  - metis=5.1.0
  - ml-collections=0.1.1
  - ml_dtypes=0.2.0
  - more-itertools=10.1.0
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - msgpack-python=1.0.5
  - mudata=0.2.3
  - multidict=6.0.4
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - natsort=8.4.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - nomkl=1.0
  - numba=0.57.1
  - numcodecs=0.11.0
  - numpy=1.24.4
  - numpy_groupies=0.9.22
  - numpyro=0.12.1
  - omnipath=1.0.7
  - openjpeg=2.5.0
  - openpyxl=3.1.2
  - openssl=3.1.2
  - opt_einsum=3.3.0
  - optax=0.1.7
  - orc=1.9.0
  - ordered-set=4.1.0
  - orjson=3.9.2
  - packaging=23.1
  - pandas=2.0.2
  - parso=0.8.3
  - partd=1.4.0
  - patsy=0.5.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.5.0
  - pims=0.6.1
  - pip=23.1.2
  - pkginfo=1.9.6
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - poetry=1.5.1=linux_pyhd8ed1ab_0
  - poetry-core=1.6.1
  - poetry-plugin-export=1.4.0
  - pooch=1.7.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=12.0.1
  - pycparser=2.21
  - pydantic=1.10.12
  - pygments=2.15.1
  - pyjwt=2.8.0
  - pynndescent=0.5.10
  - pyopenssl=23.2.0
  - pyparsing=3.1.0
  - pyproject_hooks=1.0.0
  - pyro-api=0.1.2
  - pyro-ppl=1.8.6
  - pysocks=1.7.1
  - python=3.10.4
  - python-build=0.10.0
  - python-dateutil=2.8.2
  - python-editor=1.0.4
  - python-installer=0.7.0
  - python-multipart=0.0.6
  - python-tzdata=2023.3
  - python_abi=3.10=3_cp310
  - pytorch=2.0.0=cpu_generic_py310h7ffd2bf_1
  - pytorch-lightning=2.0.6
  - pytz=2023.3
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=25.1.0
  - rapidfuzz=2.15.1
  - rdma-core=28.9
  - re2=2023.03.02
  - readchar=4.0.5
  - readline=8.2
  - referencing=0.30.1
  - requests=2.31.0
  - requests-toolbelt=1.0.0
  - rich=13.5.1
  - rpds-py=0.9.2
  - s2n=1.3.46
  - scanpy=1.9.3
  - scikit-image=0.21.0
  - scikit-learn=1.2.2
  - scipy=1.11.0
  - scvelo=0.2.5
  - scvi-tools=1.0.2
  - seaborn-base=0.12.2
  - secretstorage=3.3.3
  - session-info=1.0.0
  - setuptools=68.0.0
  - shellingham=1.5.1
  - six=1.16.0
  - sleef=3.5.1
  - slicerator=1.1.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sparse=0.14.0
  - sqlite=3.42.0
  - squidpy=1.2.2
  - stack_data=0.6.2
  - starlette=0.27.0
  - starsessions=1.3.0
  - statsmodels=0.14.0
  - stdlib-list=0.8.0
  - suitesparse=5.10.1
  - sympy=1.12
  - tbb=2021.9.0
  - tblib=1.7.0
  - texttable=1.6.7
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tomli=2.0.1
  - tomlkit=0.12.1
  - toolz=0.12.0
  - torchmetrics=0.11.4
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - trove-classifiers=2023.7.6
  - typing=3.10.0.0
  - typing_extensions=4.6.3
  - tzdata=2023c
  - ucx=1.14.1
  - umap-learn=0.5.3
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - uvicorn=0.23.2
  - validators=0.22.0
  - virtualenv=20.24.2
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.6.1
  - websockets=11.0.3
  - wheel=0.40.0
  - wrapt=1.15.0
  - xarray=2023.7.0
  - xlrd=1.2.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.7.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - zarr=2.16.1
  - zeromq=4.3.4
  - zfp=1.0.0
  - zict=3.0.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.2
  - pip:
      - adjusttext==0.8
      - annoy==1.17.3
      - arviz==0.16.1
      - cachetools==5.3.1
      - cellpose==2.2.3
      - celltypist==1.5.3
      - chex==0.1.7
      - corescpy==0.0.1
      - custom-inherit==2.4.1
      - decoupler==1.4.0
      - equinox==0.10.11
      - etils==1.4.1
      - fastremap==1.14.0
      - flax==0.7.2
      - future==0.18.3
      - google-api-core==2.11.1
      - google-auth==2.22.0
      - google-cloud-core==2.3.3
      - google-cloud-storage==2.10.0
      - google-crc32c==1.5.0
      - google-resumable-media==2.5.0
      - googleapis-common-protos==1.60.0
      - h5netcdf==1.2.0
      - igraph==0.10.6
      - imagecodecs==2023.9.4
      - install==1.3.5
      - jaxopt==0.8
      - jaxtyping==0.2.21
      - lineax==0.0.1
      - llvmlite==0.40.1
      - mizani==0.9.2
      - muon==0.1.5
      - oath==1.4.4
      - opencv-python-headless==4.8.0.76
      - orbax-checkpoint==0.3.4
      - ott-jax==0.4.3
      - pertpy==0.5.0
      - plotnine==0.12.2
      - ply==3.11
      - protobuf==4.24.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycryptodome==3.18.0
      - pyomo==6.6.1
      - pypng==0.20220715.0
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.12.2
      - pyqt6==6.5.2
      - pyqt6-qt6==6.5.2
      - pyqt6-sip==13.5.2
      - pyqtgraph==0.13.3
      - python-igraph==0.10.6
      - python-vipaccess==0.14.1
      - remotezip==0.12.1
      - reportlab==4.0.4
      - roifile==2023.8.30
      - rsa==4.9
      - scikit-misc==0.3.0
      - seaborn==0.11.2
      - sparsecca==0.3.0
      - statannotations==0.5.0
      - superqt==0.5.4
      - switchlang==0.1.0
      - tabulate==0.9.0
      - tensorstore==0.1.41
      - tifffile==2023.8.30
      - toyplot==1.0.3
      - toytree==2.0.1
      - typeguard==4.1.1
      - typing-extensions==4.7.1
      - xarray-einstats==0.6.0
