CONSTANTS_PANELS = {
    "TUQ97N": dict(col_sample_id_o="Sample ID",
                   col_sample_id="Sample",
                   col_subject="Name",
                   col_slide="Slide Id",
                   col_inflamed="Inflammation",
                   col_stricture="Stricture",
                   col_condition="Condition",
                   key_inflamed="inflamed",
                   key_uninflamed="uninflamed",
                   key_stricture="stricture",
                   col_data_dir="file_path",
                   col_object="out_file",
                   col_tangram="tangram_prediction",
                   col_segment="segmentation"),

    "XR4UZH": dict(col_sample_id_o="sampleID",
                   col_sample_id="Sample",
                   col_subject="sourceID",
                   col_slide="slide_ID",
                   col_inflamed="inflamed",
                   col_condition="disease_status",
                   key_inflamed="inflamed",
                   key_uninflamed="uninflamed",
                   col_data_dir="file_path",
                   col_object="out_file",
                   col_tangram="tangram_prediction")
}
